DSET   ^test.dat
UNDEF    -1.0E30
OPTIONS little_endian
TITLE  test data from hadsst anomalies, generated by joe's eof program
*
XDEF 20 LINEAR  -79.5 1.0
*
YDEF 20 LINEAR  10.5 1.0
*
ZDEF 1  LINEAR  1 1
*
TDEF 588  LINEAR  jan1950 1mo
*
VARS 1
sst  0  0 Monthly sst
ENDVARS

